%{
#include "templ.hpp"
%}
%defines
%union {
	char c;
	string *s;
	object *o;
}
%token <c> CHAR SX AX
%token <o> DIRECTIVE FFILE FEOF SYM
%type <o> ex
%%
templ :
	| templ AX ex		{ W($3->dump()); }
	| templ SX ex		{ W($3->eval()->value); }
	| templ ex			{ W($2->dump()); }
	| templ CHAR		{ W($2); }
;

ex :
	  SYM				
	| FFILE SYM			{ $$ = new directive(".file "+$2->eval()->value); }
	| FEOF				{ $$ = new directive(".eof"); }
	| DIRECTIVE
;

%%

