.file README.md
\# ![logo](logo/$LOGO$.png) $MODULE$: $TITLE$
\#\#\# $ABOUT$

$AUTHOR$

license: $LICENSE$

GitHub: $GITHUB$

\#\#\# ![warning](logo/$LISP$.png) Powered by bI

This program was autogened by bI system

Any program MUST HAVE scripting ability for CONFIGS and user EXTENSIONS.

bI system provides universal script engine for bI language abridged dialect
and dynamic data types C++ class tree for internal use in generated program.
