readme		= next + file @ 'README.md'		# README

# README

readme += '# ![logo](https://github.com/ponyatov/icons/raw/master/'+LOGO+'.png) '
readme += MODULE+' : '+TITLE+'\n'
readme += '### '+ABOUT+'\n'
readme += '\n'+AUTHOR+'\n'
readme += '\nlicense: '+LICENSE+'\n'
readme += '\nGitHub: '+GITHUB+'\n'
readme += '\n### ![logo](https://github.com/ponyatov/icons/raw/master/logo64x64.png) powered by bI dymanic language\n'

