readme = next + file @ 'README.md'

readme += '# ![logo](https://github.com/ponyatov/icons/raw/master/'+LOGO+'.png) '
readme += MODULE+' : '+TITLE+'\n'
readme += '### '+ABOUT+'\n'
readme += '\n'+AUTHOR+'\n'
readme += '\nlicense: '+LICENSE+'\n'
readme += '\nGitHub: https://github.com/ponyatov/Y/tree/dev/'+MODULE+'/\n'
readme += '\n### ![logo](https://github.com/ponyatov/icons/raw/master/hedge64x64.png) powered by bI dymanic language\n'

